# Basic configuration
title: Giancarlo Misasi
sub-title: SDE III @ Amazon
description: Software Engineer and pasta making enthusiast.
url: https://giancarlo-misasi.github.io
domain: giancarlo-misasi.github.io

# GitHub configuration
github: [metadata]
github_username: giancarlo-misasi

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed

# Theme configuration
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "Giancarlo Misasi"
  avatar: "/assets/images/avatar_giancarlo_misasi.jpg"
  bio: "Software Engineer and pasta making enthusiast."
  location: "North Vancouver, BC, Canada"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/giancarlo-misasi?tab=repositories"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://linkedin.com/in/giancarlo-misasi"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/giancarlo-misasi?tab=repositories"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://linkedin.com/in/giancarlo-misasi"

# Reading Files
include:
  - _pages

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
