# Site configuration
theme: jekyll-theme-tactile
title: Giancarlo Misasi
# description: Software Engineer and pasta making enthusiast.
url: https://giancarlo-misasi.github.io
domain: giancarlo-misasi.github.io
locale: en-CA

# Header configuration
header:
  avatar: "/assets/images/avatar_giancarlo_misasi.jpg"
  author: "Giancarlo Misasi"
  bio: "Software Development Engineer"
  location: "North Vancouver, BC, Canada"
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://linkedin.com/in/giancarlo-misasi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/giancarlo-misasi?tab=repositories"

# Footer configuration
footer:
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://linkedin.com/in/giancarlo-misasi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/giancarlo-misasi?tab=repositories"
    - label: "Feed"
      icon: "fa-solid fa-rss"
      url: "/feed.xml"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed

# GitHub configuration
github: [metadata]
github_username: giancarlo-misasi