# Site configuration
theme: jekyll-theme-tactile
title: Giancarlo Misasi
description: Software Engineer with over 10 years experience building cool things.
url: https://giancarlo-misasi.github.io
domain: giancarlo-misasi.github.io
locale: en-CA

# GitHub configuration
github: [metadata]
github_username: giancarlo-misasi

# Sass configuration
sass:
    style: compressed

# Fonts
fonts:
  combine:
    - url: https://fonts.googleapis.com/css?display=swap&family=
      families:
        - Montserrat
        - Dosis
      text: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

# Stylesheets
stylesheets:
  combine:
    - url: https://cdn.jsdelivr.net/combine/
      files:
        - npm/normalize.css@8.0.1/normalize.min.css
        - npm/purecss@2.1.0/build/base-min.css
        - npm/purecss@2.1.0/build/grids-min.css
        - npm/purecss@2.1.0/build/grids-responsive-min.css
  single:
    - url: https://cdn.jsdelivr.net/
      files:
        - gh/devicons/devicon@2.15.1/devicon.min.css # combine breaks due to relative paths

# Scripts
scripts:
  single:
    - url: /
      files:
        - assets/js/sentence-scroller.min.js
        - assets/js/main.min.js

# Data
giancarlo:
  avatar: "/assets/images/avatar_giancarlo_misasi.jpg"
  name: Giancarlo Misasi
  title: Software Development Engineer
  location: North Vancouver, BC, Canada
  links:
    - label: LinkedIn
      icon: devicon-linkedin-plain
      url: https://linkedin.com/in/giancarlo-misasi
    - label: GitHub
      icon: devicon-github-original
      url: https://github.com/giancarlo-misasi?tab=repositories
  tech:
    - label: java
      icon: devicon-java-plain colored
    - label: aws
      icon: devicon-amazonwebservices-original colored
    - label: cplusplus
      icon: devicon-cplusplus-plain colored
    - label: kotlin
      icon: devicon-kotlin-plain colored
    - label: raspberry pi
      icon: devicon-raspberrypi-line colored

    # - label: intellij
    #   icon: devicon-intellij-plain colored
    # - label: vim
    #   icon: devicon-vim-plain colored
    # - label: vscode
    #   icon: devicon-vscode-plain colored
    # - label: git
    #   icon: devicon-git-plain colored
    # - label: npm
    #   icon: devicon-npm-original-wordmark colored
    # - label: nodejs
    #   icon: devicon-nodejs-plain colored
    # - label: gradle
    #   icon: devicon-gradle-plain colored
    # - label: cmake
    #   icon: devicon-cmake-plain colored
    # - label: csharp
    #   icon: devicon-csharp-plain colored
    # - label: scala
    #   icon: devicon-scala-plain colored
    # - label: postgresql
    #   icon: devicon-postgresql-plain colored
    # - label: javascript
    #   icon: devicon-javascript-plain colored
    # - label: typescript
    #   icon: devicon-typescript-plain colored
    # - label: android
    #   icon: devicon-android-plain colored
    # - label: raspberry pi
    #   icon: devicon-raspberrypi-line colored
    # - label: opengl
    #   icon: devicon-opengl-plain colored
    # - label: angularjs
    #   icon: devicon-angularjs-plain colored
    # - label: .net
    #   icon: devicon-dot-net-plain colored
    # - label: jquery
    #   icon: devicon-jquery-plain colored


