# Site configuration
theme: jekyll-theme-tactile
title: Giancarlo Misasi
subtitle: SDE III @ Amazon
description: Software Engineer and pasta making enthusiast.
url: https://giancarlo-misasi.github.io
domain: giancarlo-misasi.github.io
locale: en-CA

# Header configuration
header:
  avatar: "/assets/images/avatar_giancarlo_misasi.jpg"
  author: "Giancarlo Misasi"
  bio: "Software Engineer and pasta making enthusiast."
  links:
    - label: "North Vancouver, BC, Canada"
      icon: "fas fa-fw fa-map-marker-alt"
      url: "https://goo.gl/maps/L6U4ecdbBuNpZym66"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://linkedin.com/in/giancarlo-misasi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/giancarlo-misasi?tab=repositories"

# Footer configuration
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://linkedin.com/in/giancarlo-misasi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/giancarlo-misasi?tab=repositories"
    - label: "Feed"
      icon: "fa-solid fa-rss"
      url: "/feed.xml"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed

# Non-standard directories
include:
  - _pages

# GitHub configuration
github: [metadata]
github_username: giancarlo-misasi
